matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd client
        - npm ci
      script:
        - npm run test:coverage
    - language: node_js
      node_js:
        - "stable"
      services: 
        - mongodb
      before_script:
        - cd server
        - npm ci
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script:
        - npm run test:coverage
    - language: python
      python:
        - "3.6"
      install:
        - pip install unittest
        - pip install psutil
      script:
        - cd daemon
        - python -m unittest -v
