#!/bin/bash


#Variables ==============
name="celebid"
console_prefix="[Script: $name]"
scrubber=$1
config=$2

#Functions===============
exitProcess() {
	case $1 in
		"0")
			echo $console_prefix Script ended successfully.
			exit 0
			;;
		*)
			echo $console_prefix Script ended with error \($1\).
		 	exit 1
			;;

		esac
}


#========================
#Setup
echo "$console_prefix Source scrubber: 	$scrubber"
echo "$console_prefix Source config:	$config"

cd "/"		#move to permanent dir
umask 0		#reset file mask

python3 $scrubber $config 0

#Main loop
while true; do
	python3 $scrubber $config 1
done
