#!/bin/bash


#Variables ==============
name="celebid"
console_prefix="[Script: $name]"

#Functions===============
exitProcess() {
	case $1 in
		"0")
			echo $console_prefix Script ended successfully.
			exit 0
			;;
		*)
			echo $console_prefix Script ended with error \($1\).
		 	exit 1
			;;

		esac
}


#========================
#Setup

cd "/"		#move to permanent dir
umask 0		#reset file mask

#Main loop
while true; do
	date;
	sleep 10;
done
