# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

# Controls when the workflow will run
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Server_Test:
    # The type of runner that the job will run on
    name: Server_Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: [3.6]

    steps:
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.6.0
      with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run backend tests
      run: |
        cd server
        npm ci
        mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        npm run test:coverage

  Daemon_Test:
    # The type of runner that the job will run on
    name: Daemon_Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]
        mongodb-version: [3.6]

    steps:
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.6.0
      with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run python tests
      run: |
        pip install -r daemon/requirements.txt
        cd daemon
        coverage run --branch -m unittest -v
        coverage report
    
  Client_Test:
    # The type of runner that the job will run on
    name: Client_Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: [3.6]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.6.0
      with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd client
        npm install
        cd ../server
        npm install
        
    - name: Cypress Run
      uses: cypress-io/github-action@v2
      with:
        start: npm run dev